name: Whisper
author: ggerganov
version: 1.0
based_on:  ggerganov/whisper.cpp
reference: https://github.com/ggerganov/whisper.cpp
description: |
  Makes lollms and all personas controllable using audio
help: |
  Just activate the extension and your AI will start to listen